org.gradle.jvmargs=-Dfile.encoding=UTF-8

# Basic Information
fileName=Placebo
modName=Placebo
modGroup=dev.shadowsoffire
modid=placebo
author=Shadows_of_Fire
desc=1 (one) library boi
version=9.9.0

# Dependencies
mcVersion=1.21.1
javaVersion=21
forgeVersion=21.1.187
parchmentVersion=2024.11.17-1.21.1
jeiVersion=19.21.2.313
jadeVersion=15.10.2

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
#requiredDeps=
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=283644

# Tests
enableTests=false
