org.gradle.jvmargs=-Dfile.encoding=UTF-8
# org.gradle.configuration-cache=true

# Basic Information
fileName=Placebo
modName=Placebo
modGroup=dev.shadowsoffire
modid=placebo
author=Shadows_of_Fire
desc=1 (one) library boi
version=10.0.1

# Dependencies
mcVersion=26.1.2
javaVersion=25
forgeVersion=26.1.2.64-beta
jeiVersion=29.5.0.26
jadeVersion=26.0.9

# Mixins
mixin=true
mixinVersion=0.8.7

# Publishing
#requiredDeps=
#optionalDeps=
#incompatibleDeps=
releaseType=release
modLoaders=NeoForge
curseforgeProjectId=283644

# Tests
enableTests=false
