modLoader="javafml"

loaderVersion="[2,)"

license="MIT License"

[[mods]] #mandatory

modId="placebo"

version="10.0.0-beta15"

displayName="Placebo"

authors="Shadows_of_Fire"

description='''1 (one) library boi'''

[[mixins]]
config="placebo.mixins.json"

[[dependencies.placebo]]
    modId="minecraft"
    type="required"
    versionRange="[26.1.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.placebo]]
    modId="neoforge"
    type="required"
    versionRange="[26.1.2.22-beta,)"
    ordering="NONE"
    side="BOTH"