package dev.shadowsoffire.placebo.json;

import java.util.concurrent.atomic.AtomicLong;

import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;

import dev.shadowsoffire.placebo.Placebo;
import dev.shadowsoffire.placebo.codec.PlaceboCodecs;
import dev.shadowsoffire.placebo.util.StepFunction;
import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.util.RandomSource;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.entity.ai.attributes.Attribute;
import net.minecraft.world.entity.ai.attributes.AttributeInstance;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.entity.ai.attributes.AttributeModifier.Operation;

/**
 * A Random Attribute Modifier is a data-driven template for creating {@link AttributeModifier}s.
 * <p>
 * It comes in two flavors, depending on how the modifier id is managed:
 * <ol>
 * <li>Explicit, where the id is provided in data via the {@code modifier_id} field ({@link #CODEC} / {@link #CONSTANT_CODEC}).
 * Explicit ids are stable, and must be used for any modifier that will later be identified, compared, or removed by id.</li>
 * <li>Generated, where a unique ID is created on each AttributeModifier instantiation. These modifiers cannot easily be removed.</li>
 * </ol>
 *
 * @param attribute  The attribute the created modifiers will be applicable to.
 * @param operation  The operation of the created modifiers.
 * @param value      The value range for the created modifiers.
 * @param modifierId For explicit instances, the id of the created modifiers. For generated instances, the base id minted ids are derived from.
 * @param generated  If this instance mints a fresh id for each created modifier. Use {@link #generated(Holder, Operation, StepFunction, Identifier)}
 *                   instead of passing this flag directly.
 */
public record RandomAttributeModifier(Holder<Attribute> attribute, Operation operation, StepFunction value, Identifier modifierId, boolean generated) {

    /**
     * Global counter used for generated IDs. Since the IDs intend to be throwaways, we don't care about determinism.
     */
    private static final AtomicLong GEN_COUNTER = new AtomicLong();

    public static Codec<RandomAttributeModifier> CODEC = RecordCodecBuilder.create(inst -> inst
        .group(
            BuiltInRegistries.ATTRIBUTE.holderByNameCodec().fieldOf("attribute").forGetter(RandomAttributeModifier::attribute),
            Operation.CODEC.fieldOf("operation").forGetter(RandomAttributeModifier::operation),
            StepFunction.CODEC.fieldOf("value").forGetter(RandomAttributeModifier::value),
            Identifier.CODEC.fieldOf("modifier_id").forGetter(RandomAttributeModifier::modifierId))
        .apply(inst, RandomAttributeModifier::new));

    public static Codec<RandomAttributeModifier> CONSTANT_CODEC = RecordCodecBuilder.create(inst -> inst
        .group(
            BuiltInRegistries.ATTRIBUTE.holderByNameCodec().fieldOf("attribute").forGetter(RandomAttributeModifier::attribute),
            PlaceboCodecs.enumCodec(Operation.class).fieldOf("operation").forGetter(RandomAttributeModifier::operation),
            StepFunction.CONSTANT_CODEC.fieldOf("value").forGetter(RandomAttributeModifier::value),
            Identifier.CODEC.fieldOf("modifier_id").forGetter(RandomAttributeModifier::modifierId))
        .apply(inst, RandomAttributeModifier::new));

    /**
     * Creates an explicit-id instance. All modifiers created by it will use {@code modifierId}.
     */
    public RandomAttributeModifier(Holder<Attribute> attribute, Operation operation, StepFunction value, Identifier modifierId) {
        this(attribute, operation, value, modifierId, false);
    }

    /**
     * Creates a generated-id instance, which builds a fresh modifier id of the form {@code <base>_generated_<N>} from a global
     * counter each time a modifier is created.
     * <p>
     * It will be difficult to remove modifiers generated by this. As such, only use it for apply-once-remove-never modifiers ("ephemeral" modifiers).
     */
    public static RandomAttributeModifier generated(Holder<Attribute> attribute, Operation operation, StepFunction value, Identifier base) {
        return new RandomAttributeModifier(attribute, operation, value, base, true);
    }

    /**
     * Variant of {@link #CODEC} producing {@linkplain #generated(Holder, Operation, StepFunction, Identifier) generated} instances.
     *
     * @param base The base id embedded in all instances produced by this codec, typically {@code <modid>:<prefix>}.
     */
    public static Codec<RandomAttributeModifier> generatedCodec(Identifier base) {
        return RecordCodecBuilder.create(inst -> inst
            .group(
                BuiltInRegistries.ATTRIBUTE.holderByNameCodec().fieldOf("attribute").forGetter(RandomAttributeModifier::attribute),
                Operation.CODEC.fieldOf("operation").forGetter(RandomAttributeModifier::operation),
                StepFunction.CODEC.fieldOf("value").forGetter(RandomAttributeModifier::value))
            .apply(inst, (attribute, operation, value) -> generated(attribute, operation, value, base)));
    }

    /**
     * Variant of {@link #CONSTANT_CODEC} producing {@linkplain #generated(Holder, Operation, StepFunction, Identifier) generated} instances.
     *
     * @param base The base id embedded in all instances produced by this codec, typically {@code <modid>:<prefix>}.
     */
    public static Codec<RandomAttributeModifier> constantGeneratedCodec(Identifier base) {
        return RecordCodecBuilder.create(inst -> inst
            .group(
                BuiltInRegistries.ATTRIBUTE.holderByNameCodec().fieldOf("attribute").forGetter(RandomAttributeModifier::attribute),
                PlaceboCodecs.enumCodec(Operation.class).fieldOf("operation").forGetter(RandomAttributeModifier::operation),
                StepFunction.CONSTANT_CODEC.fieldOf("value").forGetter(RandomAttributeModifier::value))
            .apply(inst, (attribute, operation, value) -> generated(attribute, operation, value, base)));
    }

    /**
     * Variant of {@link #create(RandomSource)} that uses a custom identifier.
     */
    public AttributeModifier create(Identifier id, RandomSource rand) {
        return new AttributeModifier(id, this.value.get(rand.nextFloat()), this.operation);
    }

    /**
     * Creates an {@link AttributeModifier} a randomly-selected value from the {@link #value} function.
     */
    public AttributeModifier create(RandomSource rand) {
        return create(this.effectiveId(), rand);
    }

    /**
     * Variant of {@link #createDeterministic()} that uses a custom identifier.
     */
    public AttributeModifier createDeterministic(Identifier id) {
        return new AttributeModifier(id, this.value.min(), this.operation);
    }

    /**
     * Creates a deterministic {@link AttributeModifier} using the minimum value of the {@link #value} function.
     */
    public AttributeModifier createDeterministic() {
        return createDeterministic(this.effectiveId());
    }

    public void apply(Identifier id, RandomSource rand, LivingEntity entity) {
        if (entity == null) {
            throw new RuntimeException("Attempted to apply a random attribute modifier to a null entity!");
        }
        AttributeModifier modif = this.create(id, rand);
        AttributeInstance inst = entity.getAttribute(this.attribute);
        if (inst == null) {
            Placebo.LOGGER
                .trace(String.format("Attempted to apply a random attribute modifier to an entity (%s) that does not have that attribute (%s)!", EntityType.getKey(entity.getType()), this.attribute.unwrapKey().get()));
            return;
        }
        inst.addPermanentModifier(modif);
    }

    public void apply(RandomSource rand, LivingEntity entity) {
        this.apply(this.effectiveId(), rand, entity);
    }

    /**
     * Returns the id for the next created modifier.
     */
    private Identifier effectiveId() {
        return this.generated ? this.modifierId.withSuffix("_generated_" + GEN_COUNTER.getAndIncrement()) : this.modifierId;
    }

}
